add doxygen configuration
instructlab/instructlab pull request #1167
Opened 2024-05-15 13:21 UTC by makelinux

The configuration consists of only non-default values.

To generate such configuration run:

doxygen -x | sponge Doxyfile

2024-05-15 19:24 UTC, russellb requested changes
How about a Makefile that makes it easy to run the generation?

Also, how did you decide on Doxygen vs alternatives? My impression had been Sphinx is kind of the standard for Python.

2024-05-15 19:58 UTC, makelinux commented
To generate need just run `doxygen`. Let's take a look and compare efforts and results.

2024-05-16 11:40 UTC, makelinux commented
Doxygen generates documentation for API and internals, including call graphs.

Sphinx AFAIK generates only API documentation.

2024-05-16 18:43 UTC, nathan-weinberg requested changes
Where do the generated docs get saved? Is there any docs anywhere as to how to install the utility?

2024-05-16 18:43 UTC, nathan-weinberg commented on Doxyfile
> +PROJECT_NAME           = "Instruct Lab CLI"
```suggestion
PROJECT_NAME           = "InstructLab CLI"
```

2024-05-16 19:05 UTC, makelinux commented
> Where do the generated docs get saved? Is there any docs anywhere as to how to install the utility?

Generated documentation is saved by default to directory html.

About Doxygen: https://www.doxygen.nl/download.html

2024-05-16 19:43 UTC, nathan-weinberg commented
If we decide to include this, we should include docs about installing/using it - otherwise this is just an unexplained config file

2024-05-17 07:56 UTC, makelinux commented
Yes. it can live in docs. Thank you.

2024-05-17 15:04 UTC, nathan-weinberg commented
Putting a hold on this until the docs around it I requested are added

2024-05-21 16:18 UTC, hickeyma reviewed
Preference for sphinx as well

2024-05-23 10:03 UTC, leseb commented
What's the latest on this? Are we aiming for Sphinx only? Thanks!

2024-05-23 10:58 UTC, makelinux commented
Doxygen has several unique features. Just two of them: graphs, annotated directory tree.

2024-05-23 13:20 UTC, tiran commented
Who is the target user for the documentation and how does any of these features benefit the target user?

2024-05-23 13:37 UTC, makelinux commented
Our target audience includes not only users of the ilab CLI but also developers contributing to the project. Developers, in particular, benefit significantly from Doxygen features, as it facilitates comfortable and efficient project navigation.

2024-05-24 13:38 UTC, hickeyma reviewed
@makelinux @tiran This PR and #1184 seem to be duplicates in functionality to add infrastructure to build documentation from code. Do you mind working out which implementation we are going to progress with?

2024-08-27 19:07 UTC, closed without merging