ci: add 'one-approval' label on PR that has one approval
instructlab/instructlab pull request #1178
Opened 2024-05-16 08:29 UTC by leseb

If a PR has been approved already by one of the maintainers, the PR will be labeled with 'one-approval'. This is useful for maintainers to help them determine which PR is getting close to completion and thus prioritize the review.
With the help of filters, one can look for PRs that have one approval already.

Signed-off-by: Sébastien Han <seb@redhat.com>

2024-05-16 08:30 UTC, leseb commented
@russellb PTAL

2024-05-16 08:36 UTC, leseb commented
Side note: the "Approved review" filter on PRs will only filter PRs that have two approvals (GitHub config?) so this will still be useful.

2024-05-16 18:46 UTC, russellb requested changes
I think the current config would lave the label on even after there's more than just one approval on it

2024-05-16 18:46 UTC, russellb commented on .github/mergify.yml
> +      - "#approved-reviews-by=0"
```suggestion
      - "#approved-reviews-by!=1"
```

2024-05-17 08:24 UTC, leseb commented on .github/mergify.yml
> +      - "#approved-reviews-by=0"
It's a good point, thanks!

2024-05-17 20:30 UTC, nathan-weinberg approved these changes
I don't want to get too label-happy here but this does seem like it could be a cool addition - willing to give it a shot!

2024-05-17 20:41 UTC, russellb approved these changes

2024-05-17 20:42 UTC, merged