Update README - Distrobox might also work on other linux environments
instructlab/instructlab pull request #1186
Opened 2024-05-17 16:24 UTC by josejulio

# Changes

Updated readme to suggest use of distrobox

**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
Added a note about using distrobox+fedora
I tested this on SteamOS (steam deck)

2024-05-17 17:14 UTC, jjasghar requested changes
We have a ton of confusion already in this project. Putting something the _might_ work seems like a bad idea.

2024-05-17 17:16 UTC, josejulio commented
> We have a ton of confusion already in this project. Putting something the _might_ work seems like a bad idea.

Well, it works for me - should we put a list / table of tested/tried?

2024-05-17 17:19 UTC, josejulio commented
```
It has been reported that the fedora instruction also work with distrobox. This has been tried on:
 - SteamOS using `distrobox start fedora`
```

WDYT?

2024-05-21 09:11 UTC, leseb reviewed
If we integrate this comment I'd put a warning that this is not officially supported by the project, given that we don't have any CI coverage for this case. So words of caution but I'm not opposed to this addition.

2024-05-31 16:10 UTC, josejulio commented
> If we integrate this comment I'd put a warning that this is not officially supported by the project, given that we don't have any CI coverage for this case. So words of caution but I'm not opposed to this addition.

I'll update the wording, thanks!

2024-06-19 10:07 UTC, leseb commented
@josejulio any updates on this? Thanks!

2024-07-02 14:22 UTC, josejulio commented
sorry @leseb - vacations got in the way.

I updated the note, thanks!

2024-07-02 14:45 UTC, josejulio commented
> PRs must not contain merge commits. Please rebase instead.

done

2024-07-02 14:53 UTC, josejulio commented
Checking test failures :eyes:

2024-07-02 15:42 UTC, josejulio commented
Everything seems to be green now!

2024-07-03 08:06 UTC, leseb requested changes
nits

2024-07-03 08:06 UTC, leseb commented on README.md
> +}# InstructLab 🐶 (`ilab`)
typo?

2024-07-03 08:06 UTC, leseb commented on README.md
> +> **NOTE:** This method is not officially supported by the project: It has been reported that the Fedora instructions also work with [distrobox](https://distrobox.it/) using `distrobox start fedora`.
```suggestion
> **NOTE:** This method is not officially supported by the project: It has been reported that the Fedora instructions also work with [distrobox](https://distrobox.it/) using `distrobox start fedora`. This has been tested by users on: SteamOS.
```

2024-07-03 12:07 UTC, josejulio commented on README.md
> +}# InstructLab 🐶 (`ilab`)
I'm dealing with a new keyboard with a  small enter key :-)

```suggestion
# InstructLab 🐶 (`ilab`)
```

2024-07-03 13:44 UTC, leseb reviewed
Time to squash commits please.

2024-07-03 13:48 UTC, josejulio commented
> Time to squash commits please.

done

2024-07-03 13:51 UTC, bjhargrave commented
> done

I think you should only have one commit here. The PR contains some stray commits.

2024-07-03 13:57 UTC, josejulio commented
> I think you should only have one commit here. The PR contains some stray commits.

didn't double check sorry! Looks like my squash didn't work as expected ugh - thanks!

2024-07-03 14:02 UTC, josejulio commented
Removed the stray commits, thanks!

2024-07-04 08:48 UTC, leseb approved these changes

2024-07-04 14:04 UTC, tiran approved these changes

2024-07-04 14:07 UTC, leseb commented
@jjasghar PTAL

2024-07-04 15:04 UTC, hickeyma requested changes
Thanks for pushing the text @josejulio.

I am however reluctant to add text to the README for something we do not support or test. The text reads as `This method is not officially supported by the project: It has been reported that the Fedora instructions also work...`. That is not very reassuring to me if I am a user reading the docs. 

I would suggest adding this to a blog or some other medium.

2024-07-08 17:32 UTC, josejulio commented
I understand the concerns and the reasons for not wanting to include a community based and non supported results, however, I think it would be beneficial to know what has been tried and if it worked or not. 

The instructions are focused on a  Mac and Fedora (not fully supported either!) and listing alternatives might be helpful for newcomers.

Please feel free to close if that's the consensus from maintainers, thanks!

2024-11-16 02:05 UTC, closed without merging