update ensure_server(): wait longer time to make sure server is started
instructlab/instructlab pull request #1294
Opened 2024-06-07 03:49 UTC by chudegao

**Issue resolved by this Pull Request:**
Resolves #1293

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-06-07 09:13 UTC, leseb requested changes
Other than the small nit, the approach looks good, thanks!

2024-06-07 09:13 UTC, leseb commented on src/instructlab/server.py
> +                logger.error("failed to start server")
```suggestion
                logger.error("failed to reach the API server")
```

The server did not fail, the API is just not returning anything. The server not starting is handled by the upper `while` loop.

2024-06-07 09:47 UTC, leseb reviewed
One last thing from me is to squash all commits once you're done. Thanks!

2024-06-07 11:58 UTC, leseb approved these changes

2024-06-11 13:53 UTC, nathan-weinberg approved these changes

2024-06-11 13:54 UTC, merged