add debug logging to chat
instructlab/instructlab pull request #1321
Opened 2024-06-11 10:57 UTC by makelinux

To assist debugging and reverse engineering.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-06-11 12:25 UTC, leseb reviewed
I'm supportive of incorporating more DEBUG logs, but I'm somewhat hesitant about the additional logs added here. They don't appear to be particularly relevant, though it could just be my perspective. Let's wait to hear from other maintainers and get their input on this matter. Thanks for your efforts!

2024-06-11 12:25 UTC, leseb commented on src/instructlab/chat/chat.py
> +    logger.debug("calling OpenAI API")
I'm not sure whether this is a good usage of DEBUG logs. Also, this is not calling the API, we are building the client.

2024-06-12 20:17 UTC, russellb commented
> I'm supportive of incorporating more DEBUG logs, but I'm somewhat hesitant about the additional logs added here. They don't appear to be particularly relevant, though it could just be my perspective. Let's wait to hear from other maintainers and get their input on this matter. Thanks for your efforts!

agreed

2024-06-17 23:18 UTC, russellb requested changes
i put feedback in a past comment but didn't use the official "review changes" bit to record it

2024-08-27 19:07 UTC, closed without merging