make ensure_server to wait readiness
instructlab/instructlab pull request #1322
Opened 2024-06-11 12:21 UTC by makelinux

Even when `is_alive`, the server fails to answer to `list_models`
for several seconds.
    
Retry list_models till it succeeds.
    
Fixes: #1310

2024-06-11 12:28 UTC, leseb requested changes
Similar approach than https://github.com/instructlab/instructlab/pull/1294?

2024-06-11 12:44 UTC, leseb commented
> @leseb , similar, but simpler and cleaner: no need to check `is_alive` at all.


I disagree. is_alive informs us if the process is running, while list_models indicates whether the server is responding. They serve two different but useful purposes. If either of these checks fails, we can log and return the appropriate exception, allowing us to identify the issue more precisely.

The current PR only indicates whether the server is responsive, making it difficult to pinpoint the underlying problem. The child process might have died, the llama_cpp internal server could have crashed, or there might be a bug in the OpenAI server.

Additionally, in the future, it would be better to check if someone is assigned to an issue before pushing code. If there is an assignee, go ahead and review their work. If you have an alternative approach in mind, you can include it in your review.

Thanks!

2024-06-11 12:55 UTC, makelinux commented
@leseb , why original implementation has `while server_process.is_alive():` , why **whlie is_alive**?
Why not `while not server_process.is_alive():'?
Or I am missing something?

2024-06-12 09:07 UTC, leseb commented
> @leseb , why original implementation has `while server_process.is_alive():` , why **whlie is_alive**? Why not `while not server_process.is_alive():'? Or I am missing something?

I think the idea was to wait for a server that might fail, on failure the queue will be incremented, then later we check for the empty queue or not and fail if needed. Does that help? Thanks!

2024-06-12 09:16 UTC, closed without merging