github: Run lint job when any scripts change
instructlab/instructlab pull request #1330
Opened 2024-06-11 20:08 UTC by russellb

This change address a mismatch in configuration between this workflow
and the Mergify configuration. This change makes the lint workflow
align with the Mergify configuration.

PR #1217 introduced a new script within a subdirectory under
`scripts/`. The lint job didn't run and mergify won't merge it because
it's expecting it to run.

Signed-off-by: Russell Bryant <rbryant@redhat.com>

2024-06-11 20:13 UTC, bjhargrave commented
The lint workflow does not lint sh files. It may use sh files like ruff.sh.

For the sh files in #1217, the shellcheck.yaml workflow should cover those files.

2024-06-11 20:16 UTC, russellb commented
> The lint workflow does not lint sh files. It may use sh files like ruff.sh. (which is why `scripts/*.sh` is a trigger)
> 
> For the sh files in #1217, the shellcheck.yaml workflow should already cover those files.

I'm not sure if you're suggesting changing this PR or not?

I think it still makes sense to run it when files change (because of the ruff.sh example in particular).  It could be smarter and only look out for scripts that are used within the lint job, but it's also cheap enough to run and changes ONLY touching scripts in this dir aren't that common.

2024-06-11 20:22 UTC, bjhargrave commented
> I'm not sure if you're suggesting changing this PR or not?

I guess I am saying the mergify config is driving the change in this PR  rather than changing the workflow since it actually should have been run.



> I think it still makes sense to run it when files change

At the limit, you can run all workflows when any file changes :-)

Perhaps scripts for the build (e.g. ruff.sh) and other scripts (e.g. cloud scripts) should be in disjoint folders to be clear about their function.

2024-06-11 21:06 UTC, russellb commented
> > I'm not sure if you're suggesting changing this PR or not?
> 
> I guess I am saying the mergify config is driving the change in this PR rather than changing the workflow since it actually should have been run.

... but this PR *is* changing the workflow so it runs?

2024-06-12 12:46 UTC, russellb commented on .github/workflows/lint.yml
> +      - 'scripts/**/*.sh'
Maybe? Is this wrong though?

2024-06-12 15:19 UTC, russellb commented on .github/workflows/lint.yml
> +      - 'scripts/**/*.sh'
I hear you ... all fair points, but this fixes what's broken, and it's also not important enough for me to work on further at the moment. If you feel strongly about this, I'll have it pick it back up another week (or feel free to push commits to the PR branch if you'd like)

2024-06-12 16:57 UTC, nathan-weinberg approved these changes

2024-06-12 16:57 UTC, nathan-weinberg commented on .github/workflows/lint.yml
> +      - 'scripts/**/*.sh'
Given the above convo, I am approving based on getting this fixed now. But agreed with @bjhargrave we can make this more precise later.

2024-06-13 07:53 UTC, leseb requested changes
Although, this PR is a simpler approach. I agree we should work on fixing the Mergify config instead. I've spent some time looking into it and I think https://github.com/instructlab/instructlab/pull/1346 should do. @russellb @bjhargrave PTAL, thanks!

2024-06-17 14:00 UTC, leseb commented
Can we close in favor of https://github.com/instructlab/instructlab/pull/1346?

2024-06-17 14:40 UTC, russellb commented
> Can we close in favor of #1346?

yes, thanks!

2024-06-17 14:40 UTC, closed without merging