docs: added upgrade instructions to README.md
instructlab/instructlab pull request #1424
Opened 2024-06-19 10:45 UTC by sanskriti2005

**Issue resolved by this Pull Request:**
Resolves #1381

I kind of messed things up in the last PR and lost track of commits. I'm sorry if that may have caused any inconveniences.

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-06-19 12:40 UTC, leseb approved these changes

2024-06-19 13:14 UTC, leseb requested changes
Please look into the markdown lint issues.

2024-06-21 12:57 UTC, bjhargrave approved these changes

2024-06-21 12:58 UTC, leseb approved these changes

2024-06-21 12:58 UTC, merged