Configure coverage to merge and exclude paths
instructlab/instructlab pull request #1543
Opened 2024-07-01 08:13 UTC by tiran

`coverage` is now configured to correctly merge local paths and tox paths. External InstructLab packages such as `instructlab.sdg` are excluded from coverage.

`coverage[toml]` is needed to enable `pyproject.toml` parsing in Python 3.10.

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-07-01 12:08 UTC, leseb requested changes
@tiran please see toml linter error. Thanks

2024-07-01 13:22 UTC, tiran commented
I do not agree with tomllint. Is there any way to tell it that I want each string on a separate line (like black and ruff would format Python code).

2024-07-01 13:36 UTC, leseb commented
> I do not agree with tomllint. Is there any way to tell it that I want each string on a separate line (like black and ruff would format Python code).

Taplo automatically expands arrays to multiple lines when they exceed column_width characters (80 by default). So we would need to change that I guess?

2024-07-02 08:03 UTC, leseb approved these changes

2024-07-02 18:02 UTC, nathan-weinberg approved these changes

2024-07-02 18:03 UTC, merged