feat: allow passing file as pipeline
instructlab/instructlab pull request #1668
Opened 2024-07-11 13:07 UTC by xukai92

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-07-11 13:55 UTC, xukai92 commented on src/instructlab/data/generate.py
> +    help="Data generation pipeline to use. Available: simple, full, or a valid path to a pipeline worlfow YAML file. Note that 'full' requires a larger teacher model, Mixtral-8x7b.",
the defaults are part of the SDG lib

2024-07-11 13:57 UTC, xukai92 commented on src/instructlab/data/generate.py
> +    help="Data generation pipeline to use. Available: simple, full, or a valid path to a pipeline worlfow YAML file. Note that 'full' requires a larger teacher model, Mixtral-8x7b.",
> Are we exposing the structure of this?
what does this mean? like the what exactly `simple` and `full` consists? i don't really know the answer but this doesn't change the current behavior either

2024-07-11 14:00 UTC, aakankshaduggal commented on src/instructlab/data/generate.py
> +    if value in ["simple", "full"] or os.path.isfile(value)
++ this looks great to me @xukai92

2024-07-11 14:07 UTC, aakankshaduggal approved these changes
/lgtm 
Thanks @xukai92

2024-07-11 14:12 UTC, cdoern approved these changes

2024-07-11 14:52 UTC, RobotSail approved these changes
LGTM

2024-07-11 15:21 UTC, russellb requested changes
We've been talking through the UX impact elsewhere. I don't think this interface is sufficient just yet.

The biggest problem I have is that the UX is not consistent. Prior to this change, `ilab data generate` properly handles a collection of taxonomy additions, regardless of their type (knowledge, grounded skill, freeform skill). This change assumes that the file includes a pipeline of a single type, meaning you have to stage your taxonomy additions by type and run `data generate` multiple times. I would like to have a UX that provides a consistent experience whether you're using a built-in pipeline, or a custom configuration for one. To be even more explicit -- when we're shipping a custom pipeline with a product, we don't want to have a worse UX with our product than users have using upstream.  I don't think it'll be a lot of work to achieve this.

There is extensive discussion about the configurable flows feature, including options for CLI integration, here: https://github.com/instructlab/dev-docs/pull/109 -- we need to get that sorted out

2024-07-11 15:27 UTC, markmc commented
> The biggest problem I have is that the UX is not consistent. Prior to this change, `ilab data generate` properly handles a collection of taxonomy additions, regardless of their type (knowledge, grounded skill, freeform skill).

See https://github.com/instructlab/dev-docs/pull/109#discussion_r1671554462

IMO we need to think of "full" or "simple" as a set of `(knowledge.yaml, freeform_skills.yaml, grounded_skills.yaml)` ... and the UX for custom pipelines should be about providing a custom set

2024-07-11 15:44 UTC, xukai92 commented
This PR, as the title suggests, allows "passing file as pipeline".
It does this simple thing, and nothing more.
It allows a user to do so, in or outside of the context of running it against multiple YAMLs of different types (freeform, grounded, knowledge), to use a custom pipeline.
I 100% agree with that the UX for running a custom pipeline from file against multiple YAMLs of different types is inconsistent and not good, but it's out of the scope of this PR and should be addressed as a follow up or so.

2024-07-11 15:59 UTC, xukai92 commented
@russellb please see [above](https://github.com/instructlab/instructlab/pull/1668#issuecomment-2223284298).

as a simple example, most of the time people just run `ilab data generate` against a single YAML file that they introduce. in this case this PR allows one to use `--pipeline` to specify the pipeline they want

2024-07-11 16:53 UTC, russellb commented
> This PR, as the title suggests, allows "passing file as pipeline". It does this simple thing, and nothing more. It allows a user to do so, in or outside of the context of running it against multiple YAMLs of different types (freeform, grounded, knowledge), to use a custom pipeline. I 100% agree with that the UX for running a custom pipeline from file against multiple YAMLs of different types is inconsistent and not good, but it's out of the scope of this PR and should be addressed as a follow up or so.

Yep, I understand what this does!

We've got an ordering issue here too. What needs to happen:

1. We sort out remaining design questions on how we expect configuration to work end-to-end. That's in https://github.com/instructlab/dev-docs/pull/109
2. In parallel with #1, we get `instructlab` and `sdg` PRs that can be tested together to implement the feature
3. We have to merge the `sdg` side first
4. We need a release of the `sdg` library that includes the new flow config file support
5. Then we come back to the `instructlab` PR (this one or something similar). We can merge it along with a change to `requirements.txt` that changes `instructlab>=0.1.0` to be the version number that includes the feature that is required for this feature to work.

If we merge this first, we've got `ilab` claiming a feature that doesn't exist and will just produce an error if someone tries it. We also might end up needing a different set of changes once we get to this point.

The PR is quite small, so there's not really any cost to having to hold it. Conflicts will be minimal, if at all.

2024-07-11 17:24 UTC, xukai92 commented
Cool. @russellb I'm with you that we need to have the SDG PR merged & released first.

2024-07-11 18:57 UTC, russellb commented
> Cool. @russellb I'm with you that we need to have the SDG PR merged & released first.

cool, let's make it happen this week! go team :)

2024-07-12 16:03 UTC, russellb commented on src/instructlab/data/generate.py
> +    if value in ["simple", "full"] or os.path.isfile(value)
The design we landed on is that this needs to be a directory instead of a file, so I'll update this PR to reflect that change

2024-07-12 16:21 UTC, russellb commented
@cdoern @aakankshaduggal @RobotSail i had to add an additional commit to reflect the final design and implementation based on the details in https://github.com/instructlab/dev-docs/blob/main/docs/sdg/sdg-flow-yaml.md

I tested it with the latest sdg code that includes config file support

bogus alias

```
❯ ilab data generate --num-instructions 1 --pipeline foo
Usage: ilab data generate [OPTIONS]
Try 'ilab data generate --help' for help.

Error: foo is not a valid pipeline alias ("simple" or "full") or path to a directory including pipeline configuration files.
```

before i put files in place ...

```
❯ ilab data generate --num-instructions 1 --pipeline ~/src/instructlab/customflows
...
Generating dataset failed with the following error: Error: pipeline directory (/Users/rbryant/src/instructlab/customflows) does not contain knowledge.yaml.
```

with files in place and a change to the block name ...

```
$ ilab data generate --num-instructions 1 --pipeline ~/src/instructlab/customflows
...
INFO 2024-07-12 12:15:45,160 pipeline.py:69: generate Running block: i_hacked_this_pipeline_yay
```

i also tested --pipeline simple and that's still fine

2024-07-13 01:12 UTC, russellb approved these changes
This has been tested with https://github.com/instructlab/sdg/pull/86

That PR will be merged very soon and we'll get a release out before the next `instructlab` release, so I think it's fine to go ahead and merge it.

Worst case, using this without the newer `sdg` won't break anything. The new feature just won't be fully enabled yet and the failure will be pretty clear.

2024-07-13 01:14 UTC, merged