Add signal handling to gracefully terminate vLLM server
instructlab/instructlab pull request #1679
Opened 2024-07-12 09:16 UTC by leseb

Before this patch, if `ilab model serve` received a SIGTERM, it would exit abruptly, leaving the vLLM process and its child processes orphaned.

This commit enhances the `run_vllm` function by adding a signal handler for SIGTERM. This allows the vLLM server to exit gracefully when receiving a termination signal, ensuring that resources are properly released and shutdown procedures are correctly executed.

Signed-off-by: Sébastien Han <seb@redhat.com>

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-07-13 20:12 UTC, danmcp requested changes

2024-07-13 20:12 UTC, danmcp commented on src/instructlab/model/backends/vllm.py
> +    def signal_handler(
A comment to explain how this works and why seems worth it here

2024-07-14 02:11 UTC, danmcp commented
I am assuming this output I am seeing now is related:

```
INFO 07-14 02:00:39 async_llm_engine.py:50] Engine is gracefully shutting down.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
[rank0]:     return self._loop.run_until_complete(task)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
[rank0]: asyncio.exceptions.CancelledError

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 223, in <module>
[rank0]:     uvicorn.run(app,
[rank0]:   File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/uvicorn/main.py", line 577, in run
[rank0]:     server.run()
[rank0]:   File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/uvicorn/server.py", line 65, in run
[rank0]:     return asyncio.run(self.serve(sockets=sockets))
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
[rank0]:     return runner.run(main)
[rank0]:            ^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib64/python3.11/asyncio/runners.py", line 123, in run
[rank0]:     raise KeyboardInterrupt()
[rank0]: KeyboardInterrupt
```
?

2024-07-14 02:18 UTC, n1hility approved these changes

2024-07-15 12:47 UTC, leseb commented
Putting hold for clarification with @danmcp

2024-07-15 12:49 UTC, leseb commented
> I am assuming this output I am seeing now (without this change) is related:
> 
> ```
> INFO 07-14 02:00:39 async_llm_engine.py:50] Engine is gracefully shutting down.
> [rank0]: Traceback (most recent call last):
> [rank0]:   File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
> [rank0]:     return self._loop.run_until_complete(task)
> [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
> [rank0]: asyncio.exceptions.CancelledError
> 
> [rank0]: During handling of the above exception, another exception occurred:
> 
> [rank0]: Traceback (most recent call last):
> [rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
> [rank0]:   File "<frozen runpy>", line 88, in _run_code
> [rank0]:   File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 223, in <module>
> [rank0]:     uvicorn.run(app,
> [rank0]:   File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/uvicorn/main.py", line 577, in run
> [rank0]:     server.run()
> [rank0]:   File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/uvicorn/server.py", line 65, in run
> [rank0]:     return asyncio.run(self.serve(sockets=sockets))
> [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
> [rank0]:     return runner.run(main)
> [rank0]:            ^^^^^^^^^^^^^^^^
> [rank0]:   File "/usr/lib64/python3.11/asyncio/runners.py", line 123, in run
> [rank0]:     raise KeyboardInterrupt()
> [rank0]: KeyboardInterrupt
> ```
> 
> ?

Can you try again with the latest code? Thanks

2024-07-15 13:36 UTC, JamesKunstle commented
> I am assuming this output I am seeing now (without this change) is related:
> 
> ```
> INFO 07-14 02:00:39 async_llm_engine.py:50] Engine is gracefully shutting down.
> [rank0]: Traceback (most recent call last):
> [rank0]:   File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
> [rank0]:     return self._loop.run_until_complete(task)
> [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
> [rank0]: asyncio.exceptions.CancelledError
> 
> [rank0]: During handling of the above exception, another exception occurred:
> 
> [rank0]: Traceback (most recent call last):
> [rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
> [rank0]:   File "<frozen runpy>", line 88, in _run_code
> [rank0]:   File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 223, in <module>
> [rank0]:     uvicorn.run(app,
> [rank0]:   File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/uvicorn/main.py", line 577, in run
> [rank0]:     server.run()
> [rank0]:   File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/uvicorn/server.py", line 65, in run
> [rank0]:     return asyncio.run(self.serve(sockets=sockets))
> [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
> [rank0]:     return runner.run(main)
> [rank0]:            ^^^^^^^^^^^^^^^^
> [rank0]:   File "/usr/lib64/python3.11/asyncio/runners.py", line 123, in run
> [rank0]:     raise KeyboardInterrupt()
> [rank0]: KeyboardInterrupt
> ```
> 
> ?

In my experience yes, this is expected output. This is what I'm seeing for a successful exit for my code. Makes sense since the signal being sent is the user signal.

2024-07-15 13:38 UTC, JamesKunstle approved these changes
Looks like what's working for me in my code

2024-07-15 16:59 UTC, danmcp approved these changes

2024-07-15 17:00 UTC, danmcp commented
> Putting hold for clarification with @danmcp

LGTM now.  Removing the hold.

2024-07-15 17:06 UTC, tiran approved these changes

2024-07-15 18:39 UTC, alimaredia approved these changes

2024-07-15 18:40 UTC, merged