Allow for separate judge backend option
instructlab/instructlab pull request #1700
Opened 2024-07-12 22:33 UTC by danmcp

This is to allow for cases when for example your model or base model need to be served with llama-cpp but your judge needs to be served by vllm.  That would work as is if backend isn't specified.  But as soon as you need to force a backend, currently it would force the backend to be the same for the model and judge model

Ex:

```
(venv) [ec2-user@ip-10-0-1-95 instructlab]$ ilab model evaluate --judge-model models/instructlab/granite-7b-lab --benchmark mt_bench --backend llama-cpp --judge-backend vllm
Generating answers...
WARNING 2024-07-12 22:22:51,358 evaluate.py:276: launch_server When using llama-cpp, we recommend setting max_workers to a maximum of 16
  0%|                                                                                                                                                     | 0/4 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:16<00:00, 34.06s/it]
Evaluating answers...
INFO 2024-07-12 22:25:16,422 vllm.py:149: run_vllm vLLM starting up on pid 3485 at http://127.0.0.1:36937/v1
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:18<00:00,  2.26s/it]
# SKILL EVALUATION REPORT

## MODEL
models/merlinite-7b-lab-Q4_K_M.gguf

### AVERAGE:
9.0 (across 1)

### TURN ONE:
9.0

### TURN TWO:
N/A

### ERROR RATE:
0.88
```

**Issue resolved by this Pull Request:**
Resolves #1602

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-07-12 23:56 UTC, nathan-weinberg approved these changes

2024-07-15 09:43 UTC, leseb requested changes
Please document `--judge-backend` to CHANGELOG.md.

2024-07-15 13:15 UTC, danmcp commented
> Please document `--judge-backend` to CHANGELOG.md.

We're still on the same version of ilab where evaluate hasn't been released.  evaluate itself is mentioned in the release notes but not every single option.  --backend for example is not listed explicitly there now.  It's going to be pretty spotty if I add judge-backend as is.

2024-07-15 13:20 UTC, leseb approved these changes

2024-07-15 13:28 UTC, alimaredia approved these changes

2024-07-15 13:28 UTC, merged