refactor: Remove unnecessary `export`s from scripts
instructlab/instructlab pull request #1812
Opened 2024-07-20 02:01 UTC by booxter

`export` is used to pass a variable to a subprocess. These variables are not read by any subprocesses started by the scripts. No need to export them.

**Issue resolved by this Pull Request:**
Resolves #1798

**Checklist:**

- [X] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [X] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [X] Documentation has been updated, if necessary.
- [X] Unit tests have been added, if necessary.
- [X] Integration tests have been added, if necessary.

2024-07-22 14:09 UTC, leseb commented on scripts/functional-tests.sh
>  # shellcheck disable=SC2155
This can go away too now, rigth?

2024-07-22 14:19 UTC, RobotSail commented on scripts/basic-workflow-tests.sh
> -export E2E_TEST_DIR
Why are these variables being removed? We need them to exist for this end-to-end test.

2024-07-22 14:20 UTC, RobotSail commented on scripts/functional-tests.sh
> -export CONFIG_DIR
We can't remove these variables.

2024-07-22 14:20 UTC, RobotSail commented on scripts/functional-tests.sh
> -export ILAB_CONFIGDIR_LOCATION
We can't remove these variables.

2024-07-22 14:21 UTC, RobotSail requested changes
We can't remove the variables entirely, we should just remove the `export` keyword on variables which aren't being used in subprocess calls. A number of these variables should still be declared and initialized so that their definitions can be easily found.

2024-07-22 14:49 UTC, booxter commented
> so that their definitions can be easily found

@RobotSail ack, we can leave them as `VAR=` for **documentation** purposes then. But AFAIU, technically the lines are not needed. (Because shell implicitly equates `echo $NON_EXISTING_ENVVAR` and `echo $ENVVAR_WITH_EMPTY_VALUE`.)

2024-07-22 16:47 UTC, RobotSail commented
@booxter It's important to keep these variables declared at the scope they are used at, both for documentation purposes as well as making it easier for other developers to work with these files. 

In general, our style should focus on the side of readability as opposed to just what is technically considered legal in BASH. This will ensure a more clear and consistent codebase overall.

I personally also make use of the BASH LSP extension in VSCode, so having these declared at the top-level is also very important to know where they're coming from:
https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode

2025-01-20 17:58 UTC, booxter commented
Meh. Not worth it.

2025-01-20 17:58 UTC, closed without merging