ci: update basic-workflow-tests.sh to work with vllm
instructlab/instructlab pull request #1841
Opened 2024-07-23 15:47 UTC by alimaredia

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-07-23 15:48 UTC, alimaredia commented
Blocked by: https://github.com/instructlab/instructlab/pull/1839

2024-07-23 16:31 UTC, booxter requested changes

2024-07-23 16:31 UTC, booxter commented on scripts/basic-workflow-tests.sh
> +    if [ "${MIXTRAL}" -eq 1 ] && [ "${BACKEND}" == "vllm" ]; then
`set_defaults` seems to guarantee that it's never `!= "vllm"`. Wonder if we have to check it everywhere below.

2024-07-23 16:31 UTC, booxter commented on scripts/basic-workflow-tests.sh
> +        sed -i -e 's|merlinite.*|${MIXTRAL_GPTQ_MODEL}|' "${CONFIG_HOME}/instructlab/config.yaml"
This won't work: `''` won't expand the variable

2024-07-23 16:40 UTC, booxter approved these changes
LGTM. Some of `if MIXTRAL && vllm` checks could probably be just `if MIXTRAL` because `set_defaults` guarantee that it's never one but not another.

2024-07-23 20:50 UTC, alimaredia commented
@booxter When I started this line of work I had vllm and non-vllm cases when flags for granite, mixtral, and neither were passed in. When Jason and I talked yesterday we decided that this was overkill.

The reason I left the `if Mixtral && vllm` checks were just so that it was obvious to someone new to the script that the two are intertwined. That being said I removed them, since they were somewhat of a relic of past work I'd done.

2024-07-23 22:20 UTC, booxter reviewed
Code-wise, looks correct. Which CI job utilizes the workflow?

2024-07-24 09:54 UTC, leseb approved these changes

2024-07-24 09:56 UTC, leseb commented
I tried to run the CI job manually but it failed [here](https://github.com/instructlab/instructlab/actions/runs/10074501141/job/27850757333)

2024-07-25 21:37 UTC, closed without merging