fix: have chat andgenerate use the model being actively served
instructlab/instructlab pull request #1882
Opened 2024-07-25 21:15 UTC by RobotSail

Presently, the `ilab model chat` and `ilab data generate` models require
the exact path to the model being actively served. This is a bad UX
since the path had to already have been specified correctly once
when it was initially being provided to `ilab model serve`.
Furthermore, this makes it very easy to get wrong and introduce new
bugs since we are having to propogate the model actively being used in serve.
This commit fixes that by automatically detecting the model ID and using that
for the model. This should also be fine because it is not expected that
the user will be serving more than one model at a time anyway.

Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2024-07-26 07:23 UTC, leseb requested changes

2024-07-26 07:23 UTC, leseb commented on src/instructlab/model/chat.py
> -        ):
What's the reason to stop honoring the `-m` flag here? This looks like a regression.

2024-07-26 07:23 UTC, leseb commented on src/instructlab/data/generate.py
> +    # figure out what model is running
I believe the logic should be identical to what chat was doing before this patch.

2024-07-29 16:16 UTC, booxter commented on src/instructlab/data/generate.py
> +        model = models.data[0].id if models is not None else None
so you now always override what is passed via --model arg? Do we need the argument then?

2024-07-29 16:16 UTC, booxter commented on src/instructlab/data/generate.py
> +        # Right now is_temp_server() does not check if a subprocessed vllm is up
you mean `is_temp_server_running`?

2024-07-29 16:16 UTC, booxter commented on src/instructlab/data/generate.py
> +        model = models.data[0].id if models is not None else None
is it always correct to take the first model in the list? I see the commit message claims:

```
it is not expected that
the user will be serving more than one model at a time anyway
```

But is it always true? Can't we `generate` against a different server, not the one running as `serve`? AFAIU the `api_base` can point to any `OpenAI` compatible endpoint.

2024-07-29 16:16 UTC, booxter commented on src/instructlab/data/generate.py
> +        model = models.data[0].id if models is not None else None
nit: This should probably gracefully handle a degenerate case where `data` is empty (no models are served).

2024-07-29 16:16 UTC, booxter commented on src/instructlab/data/generate.py
> +        model = models.data[0].id if models is not None else None
Is `None` a good default for `model` though? I suspect the generation will crash if you don't pass anything. Should you handle it gracefully by raising an error?

2024-07-29 16:16 UTC, booxter commented on src/instructlab/data/generate.py
> +        if backend_instance is not None:
This cleanup is already done by the `finally` section at the very end of this function. Just move this `try-except` block under the `try` started below in line 235.

2024-08-06 16:10 UTC, booxter commented
@RobotSail this is set as a blocker. Would you mind respinning it to resolve git conflicts and comments?

2024-08-06 21:03 UTC, ktam3 commented
Per convo with Oleg, closing this PR in favor of

https://github.com/instructlab/instructlab/pull/1992
https://github.com/instructlab/instructlab/pull/1990

2024-08-06 21:03 UTC, closed without merging