chore!: Update PyTorch to 2.4
instructlab/instructlab pull request #2445
Opened 2024-10-14 12:12 UTC by fabiendupont

BREAKING CHANGE: Update PyTorch to 2.4

This change updaties the default Pytorch version to 2.4. It requires AMD ROCm >=6.1.

Intel Gaudi (HPU) remains on Intel fork of PyTorch 2.3.1, knowning that Intel Gaudi software v1.18 uses PyTorch 2.4.0a0.

It also requires the other repositories to update their dependencies accordingly, so it requires some coordination.

Fixes #2437

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

2024-10-15 06:40 UTC, tiran requested changes

2024-10-15 06:40 UTC, tiran commented on requirements.txt
> +torch>=2.4.1,<2.5.0
Let's allow 2.3.x until the entire ecosystem has been moved to >=2.4.0. Also keep the comment about Intel Gaudi / Habana Labs. It's there to make sure that people do not break Intel Gaudi support by requiring an incompatible PyTorch version...

```suggestion
# Intel Gaudi software 1.17.1 has PyTorch 2.3.1a0+gitxxx pre-release
torch>=2.3.0,<2.5.0
```

2024-10-15 06:40 UTC, tiran commented on notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb
> +        "!pip install -q -U transformers accelerate peft datasets bitsandbytes trl pyarrow==14.0.1 requests==2.31.0 torch==2.4.1"
vLLM 0.6.3 has a [hard version pin](https://github.com/vllm-project/vllm/blob/v0.6.3/requirements-cuda.txt) on `torch==2.4.0`

```suggestion
        "!pip install -q -U transformers accelerate peft datasets bitsandbytes trl pyarrow==14.0.1 requests==2.31.0 torch==2.4.0"
```

2024-10-17 21:57 UTC, JamesKunstle commented
@fabiendupont @nathan-weinberg @tiran we'll need to isolate this bump and run all our tests inside a compatible image in order to manually verify that this PR will work.

2024-10-24 15:18 UTC, nathan-weinberg commented
https://github.com/instructlab/instructlab/pull/2528 will need to merge first

2024-10-25 17:58 UTC, nathan-weinberg commented
@Mergifyio rebase

2024-10-25 18:31 UTC, nathan-weinberg approved these changes

2024-10-28 15:22 UTC, jaideepr97 approved these changes
not sure anybody is still using the notebooks but lgtm

2024-10-28 15:23 UTC, merged