add -rc option for show
instructlab/instructlab pull request #2610
Opened 2024-11-10 06:45 UTC by reidliu41

- add rc option and it will remove the comments from the show output

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

2024-11-10 16:23 UTC, nathan-weinberg approved these changes

2024-11-10 21:25 UTC, danmcp commented on src/instructlab/config/show.py
> +    "--remove-comments",
Would --without-comments be better?

Then is would read as

`ilab config show --without-comments`

vs

`ilab config show --remove-comments`

2024-11-10 21:31 UTC, danmcp commented on tests/test_lab_config.py
> +    yaml_stream = ruamel.yaml.compat.StringIO()
Logic could be shared with https://github.com/instructlab/instructlab/pull/2602/files in a common method

2024-11-11 03:42 UTC, danmcp commented on src/instructlab/config/show.py
> +            if isinstance(output[key], (CommentedMap, list)):
Why include list here if show_config_without_comments doesn't do anything with lists?

2024-11-11 15:07 UTC, danmcp requested changes

2024-11-11 15:07 UTC, danmcp commented on src/instructlab/config/show.py
> +            show_config_without_comments(result)
Suggestion for a better name: `strip_comments` ?

2024-11-11 15:07 UTC, danmcp commented on src/instructlab/config/show.py
> +def show_config_without_comments(output):
Would be good to add typing info to this function

2024-11-11 15:07 UTC, danmcp commented on src/instructlab/config/show.py
> +def show_config_without_comments(output):
Variable might be better named as config?

2024-11-11 15:07 UTC, danmcp commented on src/instructlab/config/show.py
> +    """Recursively show config without comments from a ruamel.yaml data structure."""
If the method is renamed, should adjust this comment as well.

2024-11-11 15:07 UTC, danmcp commented on src/instructlab/config/show.py
> +        for key in output:
Could avoid the key lookups with:

```
        for value in output.values():
            if isinstance(value, CommentedMap):
                show_config_without_comments(value)
```

2024-11-11 23:57 UTC, danmcp commented on src/instructlab/config/show.py
> +    if isinstance(config, CommentedMap):
Is this check necessary?  If it is, it seems like the typing for the function is wrong.

2024-11-12 00:54 UTC, reidliu41 commented on src/instructlab/config/show.py
> +def strip_comments(config: CommentedMap) -> None:
seems not work for the last level, add the check is fine
```
 ilab config show -wc -k serve.vllm
gpus:
llm_family: ''
max_startup_attempts: 120

$ ilab config show -wc -k serve.vllm.gpus
Traceback (most recent call last):
AttributeError: 'NoneType' object has no attribute 'ca'
```

2024-11-12 00:59 UTC, danmcp commented on src/instructlab/config/show.py
> +def strip_comments(config: CommentedMap) -> None:
Sorry not following.  Are you saying it should fail that way for serve.vllm.gpus?

2024-11-12 01:03 UTC, reidliu41 commented on src/instructlab/config/show.py
> +def strip_comments(config: CommentedMap) -> None:
CommentedMap | Any  + isinstance would be better

2024-11-12 01:06 UTC, danmcp commented on src/instructlab/config/show.py
> +def strip_comments(config: CommentedMap) -> None:
I can live with that.  Do you not like the option of calling isinstance(result, CommentedMap) before calling strip_comments from show() ?

2024-11-12 01:11 UTC, reidliu41 commented on src/instructlab/config/show.py
> +def strip_comments(config: CommentedMap) -> None:
no... I think is ok too..haha
I just think you need to type "Any" , actually i used isinstance(result, CommentedMap) before. ok, let check it before the calling.

2024-11-12 03:45 UTC, danmcp approved these changes

2024-11-12 03:45 UTC, merged