Update README.md
instructlab/instructlab pull request #2742
Opened 2024-12-04 12:11 UTC by NAJMAJAMAL

Updating the Readme as described in the https://github.com/instructlab/instructlab/issues/2699

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

2024-12-04 14:18 UTC, cdoern requested changes

2024-12-04 14:18 UTC, cdoern commented on README.md
> +   ilab model train --pipeline full --device gpu --data-path ~/.local/share/instructlab/datasets/knowledge_train_msgs_2024-10-23T09_14_44.jsonl
```suggestion
   ilab model train --pipeline full --device coda --data-path ~/.local/share/instructlab/datasets/knowledge_train_msgs_2024-10-23T09_14_44.jsonl
```

2024-12-05 15:50 UTC, nathan-weinberg approved these changes

2024-12-05 20:32 UTC, cdoern approved these changes

2024-12-05 20:33 UTC, merged