feat: Expose document store Python API in instructlab/instructlab rag submodule
instructlab/instructlab pull request #2832
Opened 2024-12-20 12:05 UTC by dmartinol

## References
This PR relates to the task "[Dev][RAG] Expose document store Python API in instructlab/instructlab rag submodule" in the RAG project.

## Proposed interfaces
We propose two interfaces to model the ingestion and retrieval interactions with a document store, in the context of RAG pipelines:
```python
class DocumentStoreRetriever(ABC):
    @abstractmethod
    def augmented_context(self, user_query: str) -> str:...

class DocumentStoreIngestor(ABC):
    @abstractmethod
    def ingest_documents(self, input_dir) -> tuple[bool, int]:...
```

## Design notes
The actual instances are generated by factory functions that use `framework` and `type` parameters (modeled as enums)
to delegate the actual implementation to a function identified with some naming conventions.

Factory functions:
```python 
def create_document_retriever(
    framework: RagFramework,
    type: DocumentStoreType,
    document_store_config: DocumentStoreConfig,
    retriever_config: RetrieverConfig,
) -> DocumentStoreRetriever:
...

def create_document_store_ingestor(
    framework: RagFramework,
    type: DocumentStoreType,
    document_store_config: DocumentStoreConfig,
    embedding_config: EmbeddingModelConfig,
) -> DocumentStoreIngestor:
...
```

For example, in case of Milvus db with the Haystack framework, we create a `DocumentStoreRetriever` with the function `create_milvus_document_retriever` from module `instructlab.rag.haystack.document_store_retriever`.

Haystack implementation hides the pipeline details and only shows the pipeline output as a result of the Document Store APIs.

## Test functions
Test functions in  `tests/test_document_store_factory.py` can help to clarify how to consume these APIs.

## Updated dependencies
Requirements file has been updated to reflect the required dependencies.

## Minimize the PR
The changes include the implementation of the Haystack document stores for Milvus mainly to prove the effectiveness of the proposal. If you prefer, we can start with a minimal commit to only include the interfaces and the minimal dependencies (configuration and  unit test).

@anastasds @jwm4

**Checklist:**

- [X] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [X] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [X] Unit tests have been added, if necessary.
- [X] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

2025-01-06 16:11 UTC, anastasds requested changes
Suggested some simplification and had a few questions.

2025-01-06 16:11 UTC, anastasds commented on src/instructlab/rag/document_store_factory.py
> +    framework: RagFramework,
Why are we parametrizing like this? We don't need to support swapping LLM frameworks, so this machinery is nontrivial and unnecessary.

2025-01-06 16:11 UTC, anastasds commented on src/instructlab/rag/haystack/components/document_splitter.py
> +            )
Are the checks/exceptions in this class reproducing existing docling checks/exceptions? If so, we can just let it throw.

2025-01-06 16:11 UTC, anastasds commented on src/instructlab/rag/haystack/document_store_ingestor.py
> +    pipeline.add_component(instance=DocumentCleaner(), name="document_cleaner")
Are we sure we want to apply Haystack's document cleaning?

2025-01-06 16:49 UTC, anastasds commented on src/instructlab/rag/rag_configuration.py
> +        # default_factory=lambda: "ibm-granite/granite-embedding-278m-multilingual",
There's an ADR about model choice at https://github.com/instructlab/dev-docs/pull/169

2025-01-06 16:49 UTC, anastasds commented on requirements.txt
> +sentence-transformers>=3.0.0
Do we need this dependency?

2025-01-07 10:13 UTC, dmartinol commented
@anastasds Please note that the `document_splitter` might be replaced by the one available in the `docling-haystack`, whenever it will be available. 
ATM we cannot integrate it because of a dependency conflict with the `instructlab-sdg` package:
```
    instructlab-sdg 0.6.2 depends on docling<=2.8.3 and >=2.4.2
    docling-haystack 0.1.1 depends on docling<3.0.0 and >=2.9.0
```
I've added one comment [here](https://github.com/instructlab/sdg/issues/436#issuecomment-2574886485) to track the request of upgrading the `instructlab-sdg` dependencies.

2025-01-07 10:19 UTC, dmartinol commented on requirements.txt
> +sentence-transformers>=3.0.0
`sentence-transformers` package is needed if we use the `SentenceTransformersDocumentEmbedder` (at ingestion time) and `SentenceTransformersTextEmbedder` (at inference time). They are compatible with the granite embedding model and also with most of the models available on HF.
Anyway, I see the point and I'm wondering if we need to make this step configurable in some way. Assuming that we're not serving the embedding endpoint (`ilab model serve --model-path ....ibm-granite/granite-embedding-125m-english`), the alternative is what Haystack calls the [on-premise-embedders](https://docs.haystack.deepset.ai/docs/choosing-the-right-embedder#on-premise-embedders). 
What other embedding component could we use?

2025-01-07 10:19 UTC, dmartinol commented on src/instructlab/rag/rag_configuration.py
> +        # default_factory=lambda: "ibm-granite/granite-embedding-278m-multilingual",
Updated accordingly to `ibm-granite/granite-embedding-125m-english`

2025-01-07 10:20 UTC, dmartinol commented on src/instructlab/rag/haystack/components/document_splitter.py
> +            )
Actually these are the Haystack errors raised during input parameter validation, I don't think we can rely on Docling for that. Any possible exception raised by Docling will be just thrown back to the caller.

Please note that the [docling-haystack](https://github.com/DS4SD/docling-haystack/tree/main) package may probably define its own "official" version of this Haystack component, so we may dismiss ours at that time.

2025-01-07 10:32 UTC, dmartinol commented on src/instructlab/rag/haystack/components/document_splitter.py
> +            )
Raised [issue #4](https://github.com/DS4SD/docling-haystack/issues/4) to request the component to be defined.

2025-01-07 10:58 UTC, dmartinol commented on src/instructlab/rag/haystack/document_store_ingestor.py
> +    pipeline.add_component(instance=DocumentCleaner(), name="document_cleaner")
I'm not sure, but if we assume to feed the pipelines with un-processed user documentation (pdf), are we also assuming that they're all ready-to-use in the RAG ingestion pipeline?
BTW: I might be wrong, but I don't think Docling applies any cleanup to the original documents.

2025-01-07 13:36 UTC, dmartinol commented on src/instructlab/rag/document_store_factory.py
> +    framework: RagFramework,
removed the `RagFramework` type but kept the same logic to lookup the creation function based on the `DocumentStoreType` enum. Please TAL
```py
        module_name = "instructlab.rag.haystack.document_store_factory"
        module = importlib.import_module(module_name)

        function_name = f"create_{type.value}_document_retriever"
        function = getattr(module, function_name)
```

2025-01-07 13:44 UTC, dmartinol commented on tests/test_document_store_factory.py
These test functions assume that the default embedding model has already been downloaded, which is not reasonable of course. What strategy do we use for similar test cases? Is there any example already in place to anticipate the requested download before the test functions are executed?

2025-01-07 13:44 UTC, dmartinol commented on tests/test_document_store_factory.py
@anastasds @cdoern maybe you can help here

2025-01-07 13:45 UTC, jwm4 commented on requirements.txt
> +sentence-transformers>=3.0.0
Thank you for explaining, @dmartinol .  This clarifies a lot.   I think you are right that SentenceTransformersTextEmbedder is the best option.  I will see what I can do about getting this approved.

2025-01-07 14:26 UTC, anastasds commented on src/instructlab/rag/document_store_factory.py
> +        function = getattr(module, function_name)
I would still argue that, as a general policy, levels of abstraction such as this one are best not implemented until actually needed. Maybe the next document store required will not be supported in Haystack, for example. 

Code is a liability; less is better. I can see the argument that we expect to support multiple document stores, but right now that is simply not required, and the focus is on getting the simplest possible vertical slice working.

This is especially the case when getting into manually importing modules using string identifiers and `getattr` loading functions - these things can be very fragile.

2025-01-07 16:31 UTC, dmartinol commented on src/instructlab/rag/document_store_factory.py
> +        function = getattr(module, function_name)
👍 I will remove both the function lookup and the store type enum, providing an hardcoded, non-configurable implementation based on milvus.

2025-01-07 18:04 UTC, anastasds commented on src/instructlab/rag/haystack/document_store_ingestor.py
> +        pattern = "*json"
```suggestion
        pattern = "*.json"
```

2025-01-07 18:07 UTC, anastasds commented on src/instructlab/rag/haystack/document_store_retriever.py
> +    pipeline.connect("embedder.embedding", "retriever.query_embedding")
I see [in Haystack docs](https://docs.haystack.deepset.ai/docs/components) that

>To connect components in a pipeline, you need to know the names of the inputs and outputs they accept. The output of one component must be compatible with the input the subsequent component accepts. 

Having magic strings as an approach gives some pause and suggests an enum, though this is probably fine for now as we're exploring.

2025-01-07 18:12 UTC, anastasds approved these changes
Pending the discussion regarding the new dependencies, looks good to me!

2025-01-07 20:12 UTC, dmartinol commented on src/instructlab/rag/haystack/document_store_retriever.py
> +    pipeline.connect("embedder.embedding", "retriever.query_embedding")
I agree, it is definitely error prone, but for now we can't do otherwise!

2025-01-07 20:38 UTC, dmartinol commented
@anastasds 
- can we make the PR ready for review?
- what about the issue with the test functions that require the download of the default embedding model?
  - make it a real unit test with mocked embedder? (not easy but probably doable)
  - make it an integration test instead?

2025-01-10 10:15 UTC, dmartinol commented
@anastasds I moved the RAG config classes to `configuration` module and made them "private". Used same code as in your PR. If you agree with the approach, you can rebase your changes to this branch

2025-01-13 20:15 UTC, cdoern reviewed
some comments on docstrings, but nothing really major stands out here to me, looks good

2025-01-13 20:15 UTC, cdoern commented on src/instructlab/rag/document_store_factory.py
> +    document_store_uri: str,
can we add doc strings for all of these for folks unfamiliar with the functionality?

2025-01-13 20:15 UTC, cdoern commented on src/instructlab/rag/haystack/components/document_splitter.py
> +    SUPPORTED_CONTENT_FORMATS = ["json"]
should this be in `defaults.py`?

2025-01-13 20:15 UTC, cdoern commented on src/instructlab/rag/haystack/components/document_splitter.py
> +        return {"documents": split_docs}
this feels like it should be a Class not just a dict

2025-01-13 20:15 UTC, cdoern commented on src/instructlab/rag/haystack/document_store_ingestor.py
> +def _connect_components(pipeline: Pipeline):
all of these haystack methods should have doc strings please

2025-01-13 20:37 UTC, dmartinol commented on src/instructlab/rag/haystack/components/document_splitter.py
> +        return {"documents": split_docs}
This is how haystack works, can’t do differently

2025-01-14 08:06 UTC, dmartinol commented on tests/test_document_store_factory.py
Using mock testing to avoid interacting with real models

2025-01-14 16:07 UTC, courtneypacheco reviewed
Looks good! Had a few comments (mostly about test coverage)

2025-01-14 16:07 UTC, courtneypacheco commented on src/instructlab/rag/document_store.py
> +        """
Should we raise `NotImplementedError` or add `pass` since this is an interface?

Common approach: https://github.com/google/etils/blob/6ff7408dbec072e4561e393d5abac9625476df36/etils/epath/backend.py#L41

```suggestion
    @abstractmethod
    def augmented_context(self, user_query: str) -> str:
        """
        Retrieve documents from the actual store matching the given `user_query` and compute the augmented context to be used
        in a RAG chat pipeline.

        Params:
          user_query: The original user query.
        Returns:
          str: The augmented context to use in a RAG chat.
        """
        raise NotImplementedError
```

2025-01-14 16:07 UTC, courtneypacheco commented on src/instructlab/rag/document_store.py
> +        """
Same here about:

> Should we raise `NotImplementedError` or add `pass` since this is an interface?

2025-01-14 16:07 UTC, courtneypacheco commented on src/instructlab/rag/haystack/component_factory.py
> +    )
Can we add unit tests for this? Unless I missed them?

2025-01-14 16:07 UTC, courtneypacheco commented on src/instructlab/rag/haystack/component_factory.py
> +    )
Can we add unit tests for this as well?

2025-01-14 16:07 UTC, courtneypacheco commented on src/instructlab/rag/haystack/components/document_splitter.py
> +class DoclingDocumentSplitter:
Can we add unit tests for this class and its functions?

2025-01-14 16:39 UTC, dmartinol commented on src/instructlab/rag/haystack/component_factory.py
> +    )
it's covered by `test_document_store_factory.py`:
```
> pytest --cov=instructlab --cov-report term tests -k 'test_document_st'
...
src/instructlab/rag/__init__.py                                    0      0   100%
src/instructlab/rag/document_store.py                              7      0   100%
src/instructlab/rag/document_store_factory.py                      9      0   100%
src/instructlab/rag/haystack/component_factory.py                 22      3    86%
src/instructlab/rag/haystack/components/document_splitter.py      52     32    38%
src/instructlab/rag/haystack/document_store_factory.py             9      0   100%
src/instructlab/rag/haystack/document_store_ingestor.py           42      4    90%
src/instructlab/rag/haystack/document_store_retriever.py          27      0   100%
```

I can add an isolated test and verify it returns a not `None` instance if you prefer.

2025-01-14 16:43 UTC, dmartinol commented on src/instructlab/rag/document_store.py
> +        """
I agree with you, but I based this implementation from the few interfaces I found, which do the same (see https://github.com/instructlab/instructlab/blob/main/src/instructlab/llamacpp/llamacpp_convert_to_gguf.py)
I'm available to change it, of course: should we involve someone to decide b/w `pass` or `NotImplementedError`?

2025-01-14 16:49 UTC, dmartinol commented on src/instructlab/rag/haystack/components/document_splitter.py
> +class DoclingDocumentSplitter:
Sure, I can add more tests and increment the coverage which is quite low:
```
src/instructlab/rag/haystack/components/document_splitter.py      52     32    38%
```

I just want to anticipate you that sooner or later this implementation will be replace by the equivalent one provided by the `docling-haystack` package. See this [issue #4](https://github.com/DS4SD/docling-haystack/issues/4)

2025-01-14 20:38 UTC, cdoern commented on src/instructlab/rag/document_store.py
> +        """
I think if this is not a norm in ilab, we should avoid this for now and keep the current implementation.

2025-01-14 22:56 UTC, dmartinol commented
@courtneypacheco added more unit tests to increase coverage
```
src/instructlab/rag/__init__.py                                    0      0   100%
src/instructlab/rag/document_store.py                              7      0   100%
src/instructlab/rag/document_store_factory.py                      9      0   100%
src/instructlab/rag/haystack/component_factory.py                 22      0   100%
src/instructlab/rag/haystack/components/document_splitter.py      52      7    87%
src/instructlab/rag/haystack/document_store_factory.py             9      0   100%
src/instructlab/rag/haystack/document_store_ingestor.py           42      3    93%
src/instructlab/rag/haystack/document_store_retriever.py          27      0   100%
```

2025-01-15 15:45 UTC, cdoern commented
@dmartinol this is looking great! can you squash the commits before merging?

2025-01-15 15:54 UTC, dmartinol commented
> @dmartinol this is looking great! can you squash the commits before merging?
✅

2025-01-15 16:17 UTC, cdoern approved these changes
thanks for the hard work on this!

2025-01-15 16:27 UTC, nathan-weinberg approved these changes

2025-01-15 18:54 UTC, merged