update Core for README and init
instructlab/instructlab pull request #2841
Opened 2024-12-27 04:55 UTC by reidliu41

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

2025-01-06 21:00 UTC, nathan-weinberg requested changes

2025-01-06 21:00 UTC, nathan-weinberg commented on src/instructlab/config/init.py
> +            f"\n{separator}\n         Welcome to the InstructLab Core\n{guide_text}\n{separator}\n"
I think we're fine to leave CLI here, since this is an entrypoint to a CLI

2025-01-06 21:27 UTC, kelbrown20 reviewed
I think this change is a little bit more complicated then adding core because `ilab` is still suppose to be in reference to the CLI tool itself, while the "Core" package is called instructlab. I hope that makes sense. So I added some suggestions that might help with those clarifications.

2025-01-06 21:27 UTC, kelbrown20 commented on README.md
>  ## ❓ What is `ilab`
```suggestion
## ❓ What is InstructLab Core
```

2025-01-06 21:27 UTC, kelbrown20 commented on README.md
> +`ilab` is a Core tool that allows you to perform the following actions:
```suggestion
InstructLab Core is a package that contains the `ilab` command-Line Interface (CLI) tool and allows you to perform the following actions:
```
@nathan-weinberg ^^ this might need an eng tweak

2025-01-06 21:27 UTC, kelbrown20 commented on README.md
> +   📋  When installing the `ilab` Core on macOS, you may have to run the `xcode-select --install` command, installing the required packages listed.
```suggestion
   📋  When installing InstructLab Core on macOS, you may have to run the `xcode-select --install` command, installing the required packages listed.
```

2025-01-06 21:27 UTC, kelbrown20 commented on README.md
>  ### 🧰 Installing `ilab`
```suggestion
### 🧰 Installing InstructLab Core
```

2025-01-06 21:27 UTC, kelbrown20 commented on README.md
> +1. There are a few ways you can locally install the `ilab` Core. Select your preferred installation method from the following instructions. You can then install `ilab` and activate your `venv` enviro
```suggestion
1. There are a few ways you can locally install the InstructLab Core. Select your preferred installation method from the following instructions. You can then install `ilab` and activate your `venv` environment.
```

2025-01-06 21:27 UTC, kelbrown20 commented on README.md
> +     Core for interacting with InstructLab.
Same thoughts with Nathan on this one

2025-01-06 21:27 UTC, kelbrown20 commented on README.md
> +4. The InstructLab Core auto-detects your hardware and select the exact system profile that matches your machine. System profiles populate the `config.yaml` file with the proper parameter values base
@nathan-weinberg is this technically accurate? Because I thought that it was the CLI that auto detects, but this might be more orchestration, so I might be wrong

2025-01-06 21:27 UTC, kelbrown20 commented on README.md
> +the `ilab` core. The `ilab model convert` command converts the new model into quantized [GGUF](https://medium.com/@sandyeep70/ggml-to-gguf-a-leap-in-language-model-file-formats-cd5d3a6058f9) format w
```suggestion
the InstructLab core. The `ilab model convert` command converts the new model into quantized [GGUF](https://medium.com/@sandyeep70/ggml-to-gguf-a-leap-in-language-model-file-formats-cd5d3a6058f9) format which is required by the server to host the model in the `ilab model serve` command.
```

2025-01-07 04:31 UTC, reidliu41 commented on README.md
> +4. The InstructLab Core auto-detects your hardware and select the exact system profile that matches your machine. System profiles populate the `config.yaml` file with the proper parameter values base
Seems better with `Core` as a function.

2025-01-07 15:27 UTC, nathan-weinberg commented on README.md
>  ## ❓ What is `ilab`
I'd remove "the"

2025-01-07 15:28 UTC, nathan-weinberg commented on README.md
> +   📋  When installing the `ilab` Core on macOS, you may have to run the `xcode-select --install` command, installing the required packages listed.
I'd remove "the"

2025-01-07 15:28 UTC, nathan-weinberg commented on README.md
> +1. There are a few ways you can locally install the `ilab` Core. Select your preferred installation method from the following instructions. You can then install `ilab` and activate your `venv` enviro
the InstructLab Core package

2025-01-07 15:29 UTC, nathan-weinberg commented on README.md
> +the `ilab` core. The `ilab model convert` command converts the new model into quantized [GGUF](https://medium.com/@sandyeep70/ggml-to-gguf-a-leap-in-language-model-file-formats-cd5d3a6058f9) format w
Capitalize "Core" I think and add "package"

2025-01-07 15:59 UTC, kelbrown20 commented on README.md
>  ## ❓ What is `ilab`
This was a part that I wasn't sure about, but I agree, I like just InstructLab Core better

2025-01-07 15:59 UTC, kelbrown20 commented on README.md
> +`ilab` is a Core tool that allows you to perform the following actions:
^^ I like this as well

2025-01-07 16:03 UTC, kelbrown20 reviewed
I added some confirmations to Nathans comments, mostly just removing the "the" in some sections

2025-01-07 16:19 UTC, reidliu41 commented
updated

2025-01-07 16:23 UTC, nathan-weinberg commented
@reidliu41 can you response/resolve the comment threads so we know what you've looked at, please?

2025-01-07 22:14 UTC, reidliu41 commented on src/instructlab/config/init.py
> +            f"\n{separator}\n         Welcome to the InstructLab Core\n{guide_text}\n{separator}\n"
keep it, not change

2025-01-07 22:14 UTC, reidliu41 commented on src/instructlab/lab.py
> +    """Core for interacting with InstructLab.
keep it, not change

2025-01-07 22:15 UTC, reidliu41 commented on README.md
>  ## ❓ What is `ilab`
updated, and removed `the`

2025-01-07 22:16 UTC, reidliu41 commented on README.md
> +`ilab` is a Core tool that allows you to perform the following actions:
updated, but `command ` should be `Command`?

2025-01-07 22:17 UTC, reidliu41 commented on README.md
> +   📋  When installing the `ilab` Core on macOS, you may have to run the `xcode-select --install` command, installing the required packages listed.
updated `InstructLab Core` without `the`

2025-01-07 22:41 UTC, reidliu41 commented on README.md
> +the `ilab` core. The `ilab model convert` command converts the new model into quantized [GGUF](https://medium.com/@sandyeep70/ggml-to-gguf-a-leap-in-language-model-file-formats-cd5d3a6058f9) format w
updated to `InstructLab Core package`

2025-01-07 22:42 UTC, reidliu41 commented on README.md
> +4. The InstructLab Core auto-detects your hardware and select the exact system profile that matches your machine. System profiles populate the `config.yaml` file with the proper parameter values base
updated to `InstructLab Core package`

2025-01-07 22:42 UTC, reidliu41 commented on README.md
>  ### 🧰 Installing `ilab`
done

2025-01-08 14:58 UTC, nathan-weinberg commented on README.md
> +`ilab` is a Core tool that allows you to perform the following actions:
Yes agreed it should be capitalized

2025-01-08 14:59 UTC, nathan-weinberg approved these changes

2025-01-11 01:34 UTC, reidliu41 commented
@kelbrown20 could you please take a look? thanks.

2025-01-13 15:56 UTC, kelbrown20 approved these changes
Thank you got updating this @reidliu41! 
LGTM!

2025-01-13 15:57 UTC, merged