ci(lint): add shell linter - Differential ShellCheck
instructlab/instructlab pull request #933
Opened 2024-04-19 08:48 UTC by jamacku

## Description

Addition of a new job in CI workflow that scans all shell scripts in the repo using ShellCheck and reports only newly added defects.

## Motivation and Context

Differential ShellCheck is a GitHub action that performs differential ShellCheck scans on shell scripts changed via PR and reports results directly in PR.

It produces reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the `Files Changed` tab, please see below.

Documentation is available at [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme).

## Screenshots

![image](https://github.com/debezium/debezium/assets/2879818/e0f16691-907f-486d-a20e-4b569322e860)

![image](https://github.com/debezium/debezium/assets/2879818/cc842adf-04b6-425c-ae7d-c39b8dffa09b)

2024-04-24 14:45 UTC, jamacku commented
@russellb It is expected. 

On PR, it checks only changed shell scripts and reports only newly added defects by comparing two ShellCheck outputs (with and without changes introduced in PR).

On commit, it does the same (so it fails only when new defects are introduced) but uploads all detected defects to the Security Dashboard so you can have a look at them at some point.

2024-04-24 14:48 UTC, russellb commented
> @russellb It is expected.
> 
> On PR, it checks only changed shell scripts and reports only newly added defects by comparing two ShellCheck outputs (with and without changes introduced in PR).
> 
> On commit, it does the same (so it fails only when new defects are introduced) but uploads all detected defects to the Security Dashboard so you can have a look at them at some point.

What about an initial scan for all of the code already in the repo?

2024-04-24 14:54 UTC, jamacku commented
Here is a run of ShellCheck in main branch of my fork:
https://github.com/jamacku/instructlab/actions/runs/8750859113/job/24015248562#step:4:1

>List of shell scripts for scanning
>  ./containers/rocm/gfx-version.sh ./containers/rocm/remove-gfx.sh ./scripts/fmt.sh ./scripts/functional-tests.sh

The initial scan that you can see happens once the workflow is committed to the branch. But in my fork 19 defects were detected. Here is the Security Dashboard screenshot:

![image](https://github.com/instructlab/instructlab/assets/2879818/060b404e-39ce-434c-a1e9-efef2e4d4241)

2024-04-24 22:27 UTC, russellb commented
I guess I’d prefer that this work like other lint jobs where we introduce the tool with a clean full run and then any further issues are blocked at PR time when new code is introducing something that is flagged.

2024-04-25 04:40 UTC, jamacku commented
> I guess I’d prefer that this work like other lint jobs where we introduce the tool with a clean full run and then any further issues are blocked at PR time when new code is introducing something that is flagged.

With this GitHub Action, you don't have to fix old defects. PRs adding new defects will still be blocked (it does differential scans). That doesn't mean that you should not look at them, but you don't have to fix them. Also, you can mark them in the Security Dashboard as false positives (once reviewed), and they won't be shown in the list.

2024-04-25 11:30 UTC, tiran commented on containers/rocm/.shellcheckrc
> +disable=SC2086
#980 fixes the problem. I can remove the ignore file after I have rebased my PR.

2024-04-25 12:04 UTC, russellb commented
> > I guess I’d prefer that this work like other lint jobs where we introduce the tool with a clean full run and then any further issues are blocked at PR time when new code is introducing something that is flagged.
> 
> With this GitHub Action, you don't have to fix old defects. PRs adding new defects will still be blocked (it does differential scans). That doesn't mean that you should not look at them, but you don't have to fix them. Also, you can mark them in the Security Dashboard as false positives (once reviewed), and they won't be shown in the list.

Yeah, I understand. I'm saying my preference would be:

1. fix them instead of not
2. just see what gets flagged without having to go through the security dashboard.

2024-05-28 11:22 UTC, leseb commented
@jamacku are you interested in pursuing this work? I opened https://github.com/instructlab/instructlab/pull/1211 to fix all the shellcheck issues in the codebase. It'll be great to get https://github.com/instructlab/instructlab/pull/933/commits/f1148a0edf169f9d12637869392fb1f89fadc618 as well. Thanks.

2024-05-28 11:52 UTC, leseb requested changes
We need to update the `mergify.yaml` as well, please look into this PR https://github.com/instructlab/instructlab/pull/1202/files. We need something similar for shell scripts:

```
    - or:
      - and:
        - or:
          - files~='.*\.sh$'
        - check-success=shellcheck-lint
      - and:
        - -files~='.*\.sh$'
 ```

Thanks!

2024-05-28 11:52 UTC, leseb commented on .github/workflows/differential-shellcheck.yml
> +  lint:
```suggestion
  shellcheck-lint:
```

2024-05-28 12:05 UTC, leseb commented on .github/workflows/differential-shellcheck.yml
> +    branches: [ main ]
```suggestion
on:
  push:
    branches:
      - "main"
      - "release-**"
    paths:
      - ''**.sh'
  pull_request:
    branches:
      - "main"
      - "release-**"
    paths:
      - ''**.sh'
```

2024-05-28 12:22 UTC, leseb approved these changes

2024-05-28 14:09 UTC, jamacku commented
Then drop the token and permissions - https://github.com/redhat-plumbers-in-action/differential-shellcheck?tab=readme-ov-file#token

2024-05-28 14:21 UTC, closed without merging