cli: Support batch size on Linux.
instructlab/instructlab pull request #997
Opened 2024-04-25 13:16 UTC by tyll

# Changes

**Which issue is resolved by this Pull Request:**
This solves one aspect of #379

**Description of your changes:**

Training speed can increase significantly with a higher batch size. Support to easily specify it on the command-line.

2024-05-02 18:05 UTC, tyll commented
@russellb @hickeyma what's needed to get a review for this?

2024-05-02 20:35 UTC, russellb requested changes

2024-05-02 20:35 UTC, russellb commented on src/instructlab/lab.py
> +)
It looks like this is Linux-only? If so, could you update the text to indicate that?

Also, if you think about a user trying to use the tool, how should they decide if they should use this option? Is there text you could add to give any guidance?

Maybe the guidance should go in here?  https://github.com/instructlab/instructlab/blob/main/docs/gpu-acceleration.md

2024-05-23 08:51 UTC, leseb commented
@tyll do you mind addressing this review https://github.com/instructlab/instructlab/pull/997#pullrequestreview-2036839019 so we can move forward? Thanks!

2024-06-19 09:54 UTC, leseb reviewed
Apologies, we lost track of this and missed your latest update. If you're still interested in continuing this work, could you please rebase your PR? We’ll ensure it gets the attention it deserves. Thank you!

2024-10-18 02:03 UTC, closed without merging